# Generated by Django 4.1.1 on 2023-01-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_forecastpoint_forecastpoly_delete_forecast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecastpoint',
            old_name='point',
            new_name='geometry',
        ),
        migrations.RenameField(
            model_name='forecastpoly',
            old_name='polygon',
            new_name='geometry',
        ),
    ]
