# Generated by Django 4.1.1 on 2023-01-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_rename_point_forecastpoint_geometry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastpoint',
            name='active',
            field=models.IntegerField(blank=True, max_length=1),
        ),
    ]
