# Generated by Django 4.1.1 on 2023-01-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_forecastpoint_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastpoint',
            name='active',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
