# Generated by Django 4.1.1 on 2023-01-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_alter_forecastpoint__30_days_rmse_temp_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastpoint',
            name='_30_days_rmse_temp_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoint',
            name='_30_days_rmse_temp_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoint',
            name='_7_days_rmse_temp_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoint',
            name='_7_days_rmse_temp_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoint',
            name='bias_temp_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoint',
            name='bias_temp_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoint',
            name='temp_max_forecast',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoint',
            name='temp_max_observation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoint',
            name='temp_min_forecast',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoint',
            name='temp_min_observation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoint',
            name='to_date_rmse_temp_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoint',
            name='to_date_rmse_temp_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoly',
            name='_30_days_rmse_temp_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoly',
            name='_30_days_rmse_temp_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoly',
            name='_7_days_rmse_temp_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoly',
            name='_7_days_rmse_temp_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoly',
            name='bias_temp_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoly',
            name='bias_temp_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoly',
            name='temp_max_forecast',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoly',
            name='temp_max_observation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoly',
            name='temp_min_forecast',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoly',
            name='temp_min_observation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoly',
            name='to_date_rmse_temp_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpoly',
            name='to_date_rmse_temp_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
